// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4143.FrisbeeBot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;


public class RobotMap {
    public static final int xboxControllerPort = 1;
    public static SpeedController driveTrainLeftMotor;
    public static SpeedController driveTrainRightMotor;
    public static RobotDrive robotDrive;
    public static Servo shooterServo;
    public static Jaguar shooterMotor;
    public static Relay conveyor;
    public static Compressor pneumaticsCompressor;
    public static DoubleSolenoid solenoid;
    public static DoubleSolenoid shifters;
    public static void init() {
    
    //Drive Train
    driveTrainLeftMotor = new Victor(1);        
    driveTrainRightMotor = new Victor(2);
    robotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
    robotDrive.setSafetyEnabled(true);
    robotDrive.setExpiration(0.1);
    robotDrive.setSensitivity(0.5);
    robotDrive.setMaxOutput(1.0);
    
    //Servo
    shooterServo = new Servo(6);
    
    //Shooter
    shooterMotor = new Jaguar(8);
    
    //Conveyor
    conveyor = new Relay(7);
    
    //Pneumatics
    pneumaticsCompressor = new Compressor(3, 1);        
    solenoid = new DoubleSolenoid(1, 2);
    shifters = new DoubleSolenoid(3, 4);
    
    LiveWindow.addActuator("Pneumatics", "Solenoid", solenoid);
    LiveWindow.addActuator("DriveTrain", "LeftMotor", (Victor) driveTrainLeftMotor);
    LiveWindow.addActuator("DriveTrain", "RightMotor", (Victor) driveTrainRightMotor);
    LiveWindow.addActuator("Shooter", "Servo", shooterServo);
    }
}
